// Code generated by go-swagger; DO NOT EDIT.

package registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SignUpOKCode is the HTTP code returned for type SignUpOK
const SignUpOKCode int = 200

/*
SignUpOK OK

swagger:response signUpOK
*/
type SignUpOK struct {

	/*
	  In: Body
	*/
	Payload *SignUpOKBody `json:"body,omitempty"`
}

// NewSignUpOK creates SignUpOK with default headers values
func NewSignUpOK() *SignUpOK {

	return &SignUpOK{}
}

// WithPayload adds the payload to the sign up o k response
func (o *SignUpOK) WithPayload(payload *SignUpOKBody) *SignUpOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sign up o k response
func (o *SignUpOK) SetPayload(payload *SignUpOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignUpOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SignUpForbiddenCode is the HTTP code returned for type SignUpForbidden
const SignUpForbiddenCode int = 403

/*
SignUpForbidden Access Denied

swagger:response signUpForbidden
*/
type SignUpForbidden struct {
}

// NewSignUpForbidden creates SignUpForbidden with default headers values
func NewSignUpForbidden() *SignUpForbidden {

	return &SignUpForbidden{}
}

// WriteResponse to the client
func (o *SignUpForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// SignUpInternalServerErrorCode is the HTTP code returned for type SignUpInternalServerError
const SignUpInternalServerErrorCode int = 500

/*
SignUpInternalServerError Ошибка на стороне сервера

swagger:response signUpInternalServerError
*/
type SignUpInternalServerError struct {
}

// NewSignUpInternalServerError creates SignUpInternalServerError with default headers values
func NewSignUpInternalServerError() *SignUpInternalServerError {

	return &SignUpInternalServerError{}
}

// WriteResponse to the client
func (o *SignUpInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
