// Code generated by go-swagger; DO NOT EDIT.

// Package restapi RMS Users API
//
//	Users API for Racoon Media Server Project
//	Schemes:
//	  http
//	Host: 136.244.108.126
//	BasePath: /
//	Version: 1.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
