swagger: '2.0'
info:
  version: 1.1.0
  title: RMS Users API
  description: Users API for Racoon Media Server Project
host: 136.244.108.126

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  key:
    type: apiKey
    in: header
    name: x-token

tags:
  - name: users
    description: Администрирование пользователей

paths:
  /users:
    get:
      tags:
        - users
      summary: Получить список пользователей и информацию по ним
      operationId: getUsers
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - results
            properties:
              results:
                type: array
                items:
                  $ref: '#/definitions/user'
        '500':
          description: Ошибка на стороне сервера
      security:
        - key: [ ]

    post:
      tags:
        - users
      summary: Создать новый ключ пользователя
      operationId: createUser
      parameters:
        - name: user
          in: body
          schema:
            $ref: '#/definitions/user'
      responses:
        '200':
          description: OK
          schema:
            type: object
            required:
              - id
              - token
            properties:
              id:
                type: string
              token:
                type: string
        '500':
          description: Ошибка на стороне сервера
      security:
        - key: [ ]

  /users/{id}:
    delete:
      tags:
        - users
      summary: Удалить ключ пользователя
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: Ключ пользователя
          required: true
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Ключ не найден
        '500':
          description: Ошибка на стороне сервера
      security:
        - key: [ ]

definitions:
  user:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      info:
        type: string
      role:
        type: string
        enum:
          - admin
          - user
          - listener
        default: user
      telegramUser:
        type: integer
      domain:
        type: string

  principal:
    type: object
    properties:
      token:
        type: string